apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cawpaw-deployment
spec:
  selector:
    matchLabels:
      app: cawpaw
  replicas: 3
  template:
    metadata:
      labels:
        app: cawpaw
    spec:
      containers:
      - name: cawpaw
        image: defilan/cawpaw
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cawpaw
  name: cawpaw-deployment
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: cawpaw
  type: NodePort
